server:
  port: 8080
spring:
  datasource:
    url: jdbc:p6spy:mysql://10.114.29.201:3306/dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123@pwd
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
mybatis-plus:
  type-aliases-package: com.qualintech.taskcentre.entity
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:mapper/*.xml
  type-enums-package: com.qualintech.taskcentre.enums
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
